model:
  arch: video_llama
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 160
  end_sym: "###"
  low_resource: False

  frozen_llama_proj: False

  llama_model: weights/vicuna/13b_v0
  imagebind_ckpt_path: weights/imagebind
  ckpt: weights/videollama/finetune-vicuna13b-v2.pth
  llama_proj_model: weights/minigpt4/pretrained_minigpt4_13b.pth
  equip_audio_branch: False

  fusion_head_layers: 2
  max_frame_pos: 32
  fusion_header_type: seqTransf


datasets:
  webvid:
    vis_processor:
      train:
        name: alpro_video_eval
        n_frms: 8
        image_size: 224
    text_processor:
      train:
        name: blip_caption

run:
  task: video_text_pretrain


gpu_id: 0
repository_path: models/Video-LLaMA