model_base: weights/vicuna/vicuna-7b-v1.5
clip_path: weights/clip/ViT-L-14.pt
pretrain_mm_mlp_adapter: weights/vtimellm/vtimellm-vicuna-v1-5-7b-stage1/mm_projector.bin
stage2: weights/vtimellm/vtimellm-vicuna-v1-5-7b-stage2
stage3: weights/vtimellm/vtimellm-vicuna-v1-5-7b-stage3
temperature: 0.05

repository_path: models/VTimeLLM