model: openllama_peft
imagebind_ckpt_path: weights/imagebind
vicuna_ckpt_path: weights/vicuna/13b_v0
delta_ckpt_path: weights/pandagpt/pandagpt_13b_max_len_256/pytorch_model.pt
repository_path: models/PandaGPT
stage: 2
max_tgt_len: 128
lora_r: 32
lora_alpha: 32
lora_dropout: 0.1
top_p: 0.01
temperature: 1.0
max_length: 256